version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/workspace
    steps:
      - checkout
      - setup_remote_docker
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     - v1-dependencies-

      # - run:
      #     name: Install node packages
      #     command: |
      #       npm install
      
      - run:
          name: Initialize gcloud CLI to connect to Google Cloud
          command: |
            # Store service account
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

            # Initialize gcloud CLI
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE

      - run:
          name: install deployment and service
          command: |
            gcloud container clusters get-credentials buildit-devops
            gcloud components install kubectl
            kubectl apply -f ~/workspace/deployment.yaml
            echo "Successfully deployed to k8s cluster"